#include "../FactoryMethods.h"
// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "MathTypes.h"

using namespace System;
using namespace System::Runtime::InteropServices;

