#pragma once

#define SEARCH_RESULTS_PANEL "SEARCH_RESULTS_PANEL"
#define SEARCH_RESULTS_CONTROL "SEARCH_RESULTS_CONTROL"

#define HISTORY_PANEL "HISTORY_PANEL"
#define HISTORY_CONTROL "HISTORY_CONTROL"